import { type ToolConfig } from "@/types/tool";
import {
  ApiOutlined,
  BorderOuterOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  ClearOutlined,
  CodeOutlined,
  FileImageOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  KeyOutlined,
  LockOutlined,
  PictureOutlined,
} from "@ant-design/icons";
import React from "react";

const tools: ToolConfig[] = [
  {
    id: "htmlExtractor",
    name: "HTML Extractor",
    description: "Extract assets and metadata from HTML code",
    icon: <FileSearchOutlined />,
    category: "Web",
    component: React.lazy(() => import("./HtmlExtractor")),
    path: "/web/html-extractor",
  },
  {
    id: "jwtTool",
    name: "JWT Tool",
    description: "Encode, Decode and Verify JSON Web Tokens",
    icon: <KeyOutlined />,
    category: "Web",
    component: React.lazy(() => import("./JwtTool")),
    path: "/web/jwt-tool",
  },
  {
    id: "wsTool",
    name: "WebSocket Tool",
    description: "Test and debug WebSocket connections",
    icon: <ApiOutlined />,
    category: "Web",
    component: React.lazy(() => import("./WsTool")),
    path: "/web/ws-tool",
  },
  {
    id: "faviconGenerator",
    name: "Favicon Generator",
    description: "Create multi-size favicons from any image",
    icon: <FileImageOutlined />,
    category: "Web",
    component: React.lazy(() => import("./FaviconGenerator")),
    path: "/web/favicon-generator",
  },
  {
    id: "textProcessor",
    name: "Text Processor",
    description:
      "A comprehensive text processing tool with encoding, decoding, and hashing capabilities",
    icon: <FileSearchOutlined />,
    category: "Web",
    component: React.lazy(() => import("./TextProcessor")),
    path: "/web/text-processor",
  },
  {
    id: "base64ImageConverter",
    name: "Base64 to Image Converter",
    description: "Convert Base64 strings to images and vice versa",
    icon: <PictureOutlined />,
    category: "Web",
    component: React.lazy(() => import("./Base64ImageConverter")),
    path: "/web/base64-image-converter",
  },
  {
    id: "timestampConverter",
    name: "Timestamp Converter",
    description:
      "Convert between Unix timestamps and human-readable date/time formats",
    icon: <FileSearchOutlined />,
    category: "Web",
    component: React.lazy(() => import("./TimestampConverter")),
    path: "/web/timestamp-converter",
  },
  {
    id: "timezoneConverter",
    name: "Timezone Converter",
    description: "Convert date and time between different timezones",
    icon: <FileSearchOutlined />,
    category: "Web",
    component: React.lazy(() => import("./TimezoneConverter")),
    path: "/web/timezone-converter",
  },
  {
    id: "regexTester",
    name: "Regex Tester",
    description:
      "Test and validate regular expressions with live matching results",
    icon: <FileSearchOutlined />,
    category: "Web",
    component: React.lazy(() => import("./RegexTester")),
    path: "/web/regex-tester",
  },
  {
    id: "passwordGenerator",
    name: "Password Generator",
    description: "Generate secure passwords with customizable options",
    icon: <KeyOutlined />,
    category: "Web",
    component: React.lazy(() => import("./PasswordGenerator")),
    path: "/web/password-generator",
  },
  {
    id: "htmlMarkdownConverter",
    name: "HTML Markdown Converter",
    description: "Convert between HTML and Markdown formats",
    icon: <FileTextOutlined />,
    category: "Web",
    component: React.lazy(() => import("./HtmlMarkdownConverter")),
    path: "/web/html-markdown-converter",
  },
  {
    id: "fileToMarkdownConverter",
    name: "File to Markdown Converter",
    description: "Convert various file formats to Markdown",
    icon: <FileTextOutlined />,
    category: "Web",
    component: React.lazy(() => import("./FileToMarkdownConverter")),
    path: "/web/file-to-markdown-converter",
  },
  {
    id: "cronGenerator",
    name: "Cron Generator",
    description: "Generate and parse cron expressions for scheduling tasks",
    icon: <CalendarOutlined />,
    category: "Web",
    component: React.lazy(() => import("./CronGenerator")),
    path: "/web/cron-generator",
  },
  {
    id: "cssGradientGenerator",
    name: "CSS Gradient Generator",
    description: "Generate beautiful CSS gradients with visual controls",
    icon: <BorderOuterOutlined />,
    category: "Web",
    component: React.lazy(() => import("./CssGradientGenerator")),
    path: "/web/css-gradient-generator",
  },
  {
    id: "codeFormatter",
    name: "Code Formatter",
    description:
      "Format and beautify code with Prettier for multiple languages",
    icon: <CodeOutlined />,
    category: "Web",
    component: React.lazy(() => import("./CodeFormatter")),
    path: "/web/code-formatter",
  },
  {
    id: "dateCalculator",
    name: "Date Calculator",
    description:
      "Calculate differences between dates or add/subtract time units from a date",
    icon: <CalendarOutlined />,
    category: "Web",
    component: React.lazy(() => import("./DateCalculator")),
    path: "/web/date-calculator",
  },
  {
    id: "numberBaseConverter",
    name: "Number Base Converter",
    description:
      "Convert numbers between different bases (binary, octal, decimal, hexadecimal, and custom bases)",
    icon: <CalculatorOutlined />,
    category: "Web",
    component: React.lazy(() => import("./NumberBaseConverter")),
    path: "/web/number-base-converter",
  },
  {
    id: "textCounter",
    name: "Text Counter",
    description:
      "Count characters, words, sentences, paragraphs and other statistics in text",
    icon: <FileTextOutlined />,
    category: "Web",
    component: React.lazy(() => import("./TextCounter")),
    path: "/web/text-counter",
  },
  {
    id: "ymlPropertiesConverter",
    name: "YML Properties Converter",
    description:
      "Convert between YML and Properties formats for configuration files",
    icon: <FileTextOutlined />,
    category: "Web",
    component: React.lazy(() => import("./YmlPropertiesConverter")),
    path: "/web/yml-properties-converter",
  },
  // {
  //   id: "pdfConverter",
  //   name: "PDF Converter",
  //   description: "Convert PDF files to images or extract text from PDFs",
  //   icon: <FilePdfOutlined />,
  //   category: "Web",
  //   component: React.lazy(() => import("./PdfConverter")),
  //   path: "/web/pdf-converter",
  // },
  // {
  //   id: "pdfManager",
  //   name: "PDF Manager",
  //   description: "Merge or split PDF files with advanced options",
  //   icon: <FilePdfOutlined />,
  //   category: "Web",
  //   component: React.lazy(() => import("./PdfManager")),
  //   path: "/web/pdf-manager",
  // },
  // {
  //   id: "pdfCompressor",
  //   name: "PDF Compressor",
  //   description: "Compress PDF files to reduce file size with advanced compression options",
  //   icon: <CompressOutlined />,
  //   category: "Web",
  //   component: React.lazy(() => import("./PdfCompressor")),
  //   path: "/web/pdf-compressor",
  // },
  {
    id: "encodingConverter",
    name: "Encoding Converter",
    description:
      "Convert text between different encoding formats (Base64, URL, Unicode, HTML entities, etc.)",
    icon: <CodeOutlined />,
    category: "Web",
    component: React.lazy(() => import("./EncodingConverter")),
    path: "/web/encoding-converter",
  },
  {
    id: "textSpaceStripper",
    name: "Text Space Stripper",
    description:
      "Remove unwanted spaces and newlines from text using various modes",
    icon: <ClearOutlined />,
    category: "Web",
    component: React.lazy(() => import("./TextSpaceStripper")),
    path: "/web/text-space-stripper",
  },
  {
    id: "cryptoTools",
    name: "Crypto Tools",
    description:
      "Various cryptographic tools for hashing, encryption, and encoding",
    icon: <LockOutlined />,
    category: "Web",
    component: React.lazy(() => import("./CryptoTools")),
    path: "/web/crypto-tools",
  },
  {
    id: "iconDesigner",
    name: "Icon Designer",
    description: "Design and export icons in various styles and formats",
    icon: <PictureOutlined />,
    category: "Web",
    component: React.lazy(() => import("./IconDesigner")),
    path: "/web/icon-designer",
  },
  {
    id: "httpTester",
    name: "HTTP Request Tester",
    description:
      "Test HTTP requests with various methods, headers, and request bodies.",
    icon: <PictureOutlined />,
    category: "Web",
    component: React.lazy(() => import("./HttpTester")),
    path: "/web/http-tester",
  },
];

export default tools;
